{ config, pkgs, lib, ... }:
# niri config generated by HM so its accent colors follow the Stylix scheme
# (focus ring, tab indicator, overview backdrop). niri isn't an official
# Stylix target, so colors are pulled from config.lib.stylix.colors here.
# Edit this file + rebuild to tweak niri.
let
  c = config.lib.stylix.colors.withHashtag;
in
{
  xdg.configFile."niri/config.kdl".text = ''
    // niri config — accent colors from Stylix. Edit + rebuild.
    input {
        keyboard {
            xkb {
                layout "us"
                // Caps handled by keyd (tap=Esc, hold=Super). Right Alt = Compose (æøå).
                options "compose:ralt"
            }
            repeat-delay 300
            repeat-rate 33
            numlock
        }
        touchpad {
            tap
            dwt
            natural-scroll
            scroll-method "two-finger"
        }
        focus-follows-mouse max-scroll-amount="0%"
    }

    overview {
        backdrop-color "${c.base00}"
    }

    layout {
        gaps 7
        center-focused-column "never"

        preset-column-widths {
            proportion 0.33333
            proportion 0.5
            proportion 0.66667
        }
        default-column-width { proportion 0.5; }
        preset-window-heights {
            proportion 0.33333
            proportion 0.5
            proportion 0.66667
        }

        focus-ring {
            width 3
            active-color "${c.base0C}"
            inactive-color "${c.base03}"
        }

        border { off; }
        shadow { off; }

        tab-indicator {
            gap 5
            width 10
            length total-proportion=1.0
            position "right"
            gaps-between-tabs 5
            corner-radius 12
            active-color "${c.base0A}"
            inactive-color "${c.base00}"
            urgent-color "${c.base08}"
        }
    }

    spawn-at-startup "swaybg" "--mode" "fill" "--image" "/home/danielh/.local/share/wallpaper.png"
    // waybar runs as a systemd user service (programs.waybar.systemd.enable)
    spawn-at-startup "blueman-applet"
    // polkit authentication agent (GUI password prompts for mount/nm/fwupd)
    spawn-at-startup "${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1"

    prefer-no-csd

    cursor {
        xcursor-theme "Adwaita"
        xcursor-size 24
        hide-when-typing
    }

    hotkey-overlay {
        skip-at-startup
    }

    screenshot-path "~/Pictures/niri-screenshot-%Y-%m-%d-%H-%M-%S.png"

    window-rule {
        geometry-corner-radius 12
        clip-to-geometry true
    }

    // New windows open at half width (niri default column = 0.5). Mod+F maximizes.

    window-rule {
        match app-id=r#"^org\.pulseaudio\.pavucontrol$"#
        match app-id="blueman-manager"
        match app-id="^nm-connection-editor$"
        open-floating true
        opacity 0.95
        default-column-width { fixed 720; }
        default-window-height { fixed 640; }
    }

    window-rule {
        match title="^Picture-in-Picture$"
        open-floating true
    }

    binds {
        Mod+Shift+Slash { show-hotkey-overlay; }

        // Apps
        Mod+Return { spawn "ghostty"; }
        Mod+D      { spawn "fuzzel"; }
        Mod+B      { spawn "zen-beta"; }
        Mod+Q      { close-window; }

        // Utilities
        Mod+V       { spawn "clipboard-menu"; }
        Mod+Shift+P { spawn "power-menu"; }
        Mod+Ctrl+L  { spawn "swaylock" "-f"; }
        Mod+Shift+N { spawn "swaync-client" "-t" "-sw"; }

        // Focus
        Mod+Left  { focus-column-left; }
        Mod+Right { focus-column-right; }
        Mod+Up    { focus-window-up; }
        Mod+Down  { focus-window-down; }
        Mod+H     { focus-column-left; }
        Mod+L     { focus-column-right; }
        Mod+K     { focus-window-up; }
        Mod+J     { focus-window-down; }

        // Move
        Mod+Shift+Left  { move-column-left; }
        Mod+Shift+Right { move-column-right; }
        Mod+Shift+H     { move-column-left; }
        Mod+Shift+L     { move-column-right; }
        Mod+Shift+K     { move-window-up; }
        Mod+Shift+J     { move-window-down; }

        // Workspaces
        Mod+1 { focus-workspace 1; }
        Mod+2 { focus-workspace 2; }
        Mod+3 { focus-workspace 3; }
        Mod+4 { focus-workspace 4; }
        Mod+Shift+1 { move-column-to-workspace 1; }
        Mod+Shift+2 { move-column-to-workspace 2; }
        Mod+Shift+3 { move-column-to-workspace 3; }
        Mod+Shift+4 { move-column-to-workspace 4; }
        Mod+Page_Down { focus-workspace-down; }
        Mod+Page_Up   { focus-workspace-up; }

        // Layout
        Mod+R          { switch-preset-column-width; }
        Mod+F          { maximize-column; }
        Mod+Shift+F    { fullscreen-window; }
        Mod+Comma      { consume-window-into-column; }
        Mod+Period     { expel-window-from-column; }
        Mod+Minus      { set-column-width "-10%"; }
        Mod+Equal      { set-column-width "+10%"; }

        // Overview
        Mod+Tab { toggle-overview; }

        // Screenshots (fuzzel menu; Shift+Print = niri's built-in region tool)
        Print       { spawn "screenshot-menu"; }
        Shift+Print { screenshot; }

        // Session
        Mod+Shift+E { quit; }

        // Volume / brightness (OSD popups via swayosd)
        XF86AudioRaiseVolume  { spawn "swayosd-client" "--output-volume" "raise"; }
        XF86AudioLowerVolume  { spawn "swayosd-client" "--output-volume" "lower"; }
        XF86AudioMute         { spawn "swayosd-client" "--output-volume" "mute-toggle"; }
        XF86MonBrightnessUp   { spawn "swayosd-client" "--brightness" "raise"; }
        XF86MonBrightnessDown { spawn "swayosd-client" "--brightness" "lower"; }
    }
  '';
}
