{ config, pkgs, lib, ... }:
# Shell stack ported from ~/dotfiles (Stow) into native Home Manager.
# zinit -> HM's built-in plugin handling; Arch-specific bits (nvm at
# /usr/share/nvm, ~/.bun) replaced with Nix-provided node/bun.
{
  programs.zsh = {
    enable = true;
    enableCompletion = true;
    autosuggestion.enable = true;
    syntaxHighlighting.enable = true;
    historySubstringSearch.enable = true;
    defaultKeymap = "viins"; # bindkey -v
    history = {
      size = 50000;
      save = 50000;
      ignoreDups = true;
      share = true;
    };

    shellAliases = {
      # editor / venv
      vim = "nvim";
      vi = "nvim";
      av = "source .venv/bin/activate";
      # eza
      ls = "eza --color=auto";
      ll = "eza --color=auto -l";
      la = "eza --color=auto -la";
      # git
      gs = "git status";
      ga = "git add";
      gc = "git commit -m";
      gp = "git push";
      gpl = "git pull";
      gb = "git branch";
      gco = "git checkout";
      gm = "git merge";
      gr = "git rebase";
      gl = "git log --oneline --graph --decorate --color=always";
      gst = "git stash";
      gapply = "git stash apply";
      gd = "git diff";
      gt = "git tag";
      gf = "git fetch";
      grs = "git reset";
      gshow = "git show";
      fu = "fuck";
    };

    initContent = ''
      # clipboard aliases (Wayland)
      if command -v wl-copy &> /dev/null; then
        alias pbcopy="wl-copy"
        alias pbpaste="wl-paste"
      fi

      # copy the previous command's output to the clipboard
      copy-last-output() {
        local output=$(fc -ln -1 | sh 2>&1)
        echo "$output" | pbcopy
        echo "Last command output copied to clipboard!"
      }
      bindkey -s '^y' 'copy-last-output\n'

      # accept autosuggestion with Ctrl-l
      bindkey '^l' autosuggest-accept

      # yazi wrapper that cd's to the last visited directory
      function y() {
        local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
        yazi "$@" --cwd-file="$tmp"
        if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
          cd -- "$cwd"
        fi
        rm -f -- "$tmp"
      }

      # command-correction: pay-respects (thefuck was removed from nixpkgs 26.05).
      # Rust, fast enough to init eagerly; `--alias fuck` keeps the old muscle memory.
      if command -v pay-respects &>/dev/null; then
        eval "$(pay-respects zsh --alias fuck)"
      fi

      # vi-mode clipboard integration: y* copies to, p/P pastes from wl-clipboard
      if command -v wl-copy &>/dev/null; then
        vi-yank-clip() { zle vi-yank; printf '%s' "$CUTBUFFER" | wl-copy; }
        vi-yank-eol-clip() { zle vi-yank-eol; printf '%s' "$CUTBUFFER" | wl-copy; }
        vi-put-after-clip() { CUTBUFFER="$(wl-paste --no-newline 2>/dev/null)"; zle vi-put-after; }
        vi-put-before-clip() { CUTBUFFER="$(wl-paste --no-newline 2>/dev/null)"; zle vi-put-before; }
        zle -N vi-yank-clip
        zle -N vi-yank-eol-clip
        zle -N vi-put-after-clip
        zle -N vi-put-before-clip
        bindkey -M vicmd 'y' vi-yank-clip
        bindkey -M vicmd 'Y' vi-yank-eol-clip
        bindkey -M vicmd 'p' vi-put-after-clip
        bindkey -M vicmd 'P' vi-put-before-clip
      fi
    '';
  };

  # Prompt — vendored from ~/dotfiles/starship, generated by HM.
  programs.starship = {
    enable = true;
    enableZshIntegration = true;
    settings = builtins.fromTOML (builtins.readFile ./starship.toml);
  };

  # Shell history (ported settings)
  programs.atuin = {
    enable = true;
    enableZshIntegration = true;
    settings = {
      enter_accept = true;
      sync.records = true;
    };
  };

  programs.zoxide = {
    enable = true;
    enableZshIntegration = true;
  };

  # Per-project dev shells: `.envrc` with `use flake` auto-loads on cd.
  programs.direnv = {
    enable = true;
    nix-direnv.enable = true;
  };

  programs.eza.enable = true;

  programs.git = {
    enable = true;
    userName = "DanielH";
    userEmail = "danielhoj1990@gmail.com";
    extraConfig.init.defaultBranch = "main";
  };

  programs.lazygit.enable = true;

  home.sessionVariables = {
    EDITOR = "nvim";
    VISUAL = "nvim";
    NODE_OPTIONS = "--no-network-family-autoselection";
    # Global npm installs land in a user-writable prefix so `npm i -g` works on
    # NixOS (for tools not in nixpkgs, e.g. pi's ecosystem plugins: pi-vim,
    # pi-subagents, pi-memory, pi-mcp-adapter, pi-observational-memory).
    NPM_CONFIG_PREFIX = "${config.home.homeDirectory}/.npm-global";
  };
  home.sessionPath = [ "${config.home.homeDirectory}/.npm-global/bin" ];

  home.packages = with pkgs; [
    eza
    zoxide
    pay-respects   # thefuck replacement (thefuck removed in nixpkgs 26.05)
    fzf
    # nodejs_22 + bun moved to ./dev.nix (language toolchains grouped there)
  ];
}
